import '~/styles/globals.css';

import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';

import { LOGO_PATH } from './constants/path';

import { TRPCReactProvider } from '~/trpc/react';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata = {
  title: 'Barbie Gym',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: `${LOGO_PATH}` }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
